[template]
prefix = "tomcat"
keys = [
	"Xmx",
	"Xms"
]

src = "catalina_start.sh.tmpl"
dest = "catalina_start.sh"
mode = "0775"

reload_cmd = """
	/usr/local/tomcat/bin/catalina.sh stop -force && \
	/usr/local/tomcat/bin/catalina_start.sh start
"""
