[template]
src = "server.xml.tmpl"
dest = "/usr/local/tomcat/conf/server.xml"

check_cmd = """
	/usr/local/tomcat/bin/catalina.sh configtest
"""

reload_cmd = """
	/usr/local/tomcat/bin/catalina.sh stop -force && \
	/usr/local/tomcat/bin/catalina.sh start
"""
