# Copyright 2018 The OpenPitrix Authors. All rights reserved.
# Use of this source code is governed by a Apache license
# that can be found in the LICENSE file.

[template]
src = "simple.toml.tmpl"
dest = "simple.toml"

check_cmd = """
	echo simple.toml check_cmd
"""

reload_cmd = """
	echo simple.toml reload_cmd
"""
