[template]
src = "tomcat-users.xml.tmpl"
dest = "tomcat-users.xml"

prefix = "tomcat"
keys = [
	"user",
	"password"
]

reload_cmd = """
	/usr/local/tomcat/bin/catalina.sh stop -force && \
	/usr/local/tomcat/bin/catalina.sh start
"""
